system:
  host: 0.0.0.0
  port: 8888
  env: debug
  start_time: "2024-12-22"
  machine_id: 1
log:
  filename: server.log
  max_size: 200
  max_age: 30
  max_backups: 7
  level: "info"
  format: "json"
  buffer_size: 256
  compress: true
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  db: blog
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: 127.0.0.1
  port: 6379
  password: redis
  db: 0
  pool_size: 100
es:
  host: 127.0.0.1
  port: 9200
jwt:
  secret: 2024724
  expires: 7
  issuer: server
  refresh_threshold: 1
captcha:
  open: false
  key_long: 6
  img_width: 240
  img_height: 80
upload:
  size: 20
  path: uploads/images
