version: '3'

services:
  mysql:
    image: mysql:8.0.39
    container_name: blog-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_MAX_ALLOWED_PACKET: 16M
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    command:
      --default-authentication-plugin=mysql_native_password
      --max_connections=50
      --innodb_buffer_pool_size=256M
      --performance_schema=off
    deploy:
      resources:
        limits:
          memory: 512M
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:5.0.5
    container_name: blog-redis
    command: redis-server --requirepass redis --maxmemory 128mb --maxmemory-policy allkeys-lru
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 128M
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: elasticsearch:8.15.0
    container_name: blog-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          memory: 512M
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q 'status.*green\\|status.*yellow'"]
      interval: 30s
      timeout: 10s
      retries: 3

  blog-backend:
    build: .
    container_name: blog-backend
    depends_on:
      - mysql
      - redis
      - elasticsearch
    volumes:
      - ./data/uploads:/app/uploads
    deploy:
      resources:
        limits:
          memory: 256M
    restart: always
    healthcheck:
      test: ["CMD", "pidof", "blog_server"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: blog-nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/logs:/var/log/nginx
    depends_on:
      - blog-backend
    restart: always
