version: "3"

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.9.1
    environment:
      - node.name=elasticsearch
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    restart: always

  mysql:
    image: mysql:8.0-debian
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # root密码
      MYSQL_DATABASE: blog # 初始数据库
      TZ: Asia/Shanghai # 时区
    ports:
      - "3306:3306" # 端口映射

  redis:
    image: redis:7.4.1
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis
    restart: always
